const JOB_STATUSES = [
  "NEW",
  "REVIEWING",
  "ASSIGNED",
  "ACCEPTED",
  "IN_PROGRESS",
  "COMPLETED",
  "CONFIRMED",
  "CANCELLED",
  "REJECTED"
];

const CUSTOMER_CONFIRMABLE_STATUS = "COMPLETED";
const CUSTOMER_REVIEWABLE_STATUS = "CONFIRMED";

const PROVIDER_STATES = [
  "REGISTERED",
  "PENDING_VERIFICATION",
  "APPROVED",
  "REJECTED",
  "DISABLED"
];

const PROVIDER_STATE_TRANSITIONS = {
  REGISTERED: ["REJECTED"],
  PENDING_VERIFICATION: ["APPROVED", "REJECTED"],
  APPROVED: ["DISABLED"],
  REJECTED: [],
  DISABLED: ["APPROVED"]
};

const OPERATOR_TRANSITIONS = {
  NEW: ["REVIEWING", "CANCELLED", "REJECTED"],
  REVIEWING: ["ASSIGNED", "CANCELLED", "REJECTED"],
  ASSIGNED: ["ACCEPTED", "CANCELLED", "REJECTED"],
  ACCEPTED: ["IN_PROGRESS", "CANCELLED"],
  IN_PROGRESS: ["COMPLETED", "CANCELLED"],
  COMPLETED: [],
  CONFIRMED: [],
  CANCELLED: [],
  REJECTED: []
};

module.exports = {
  CUSTOMER_CONFIRMABLE_STATUS,
  CUSTOMER_REVIEWABLE_STATUS,
  JOB_STATUSES,
  OPERATOR_TRANSITIONS,
  PROVIDER_STATES,
  PROVIDER_STATE_TRANSITIONS
};
