const JOB_STATUSES = [
  "NEW",
  "REVIEWING",
  "SCHEDULED",
  "ASSIGNED",
  "IN_PROGRESS",
  "COMPLETED",
  "CONFIRMED",
  "CANCELLED",
  "REJECTED"
];

const CUSTOMER_CONFIRMABLE_STATUS = "COMPLETED";
const CUSTOMER_REVIEWABLE_STATUS = "CONFIRMED";

const OPERATOR_TRANSITIONS = {
  NEW: ["REVIEWING", "CANCELLED", "REJECTED"],
  REVIEWING: ["CANCELLED", "REJECTED"],
  SCHEDULED: ["CANCELLED", "REJECTED"],
  ASSIGNED: ["IN_PROGRESS", "CANCELLED", "REJECTED"],
  IN_PROGRESS: ["COMPLETED", "CANCELLED"],
  COMPLETED: [],
  CONFIRMED: [],
  CANCELLED: [],
  REJECTED: []
};

module.exports = {
  CUSTOMER_CONFIRMABLE_STATUS,
  CUSTOMER_REVIEWABLE_STATUS,
  JOB_STATUSES,
  OPERATOR_TRANSITIONS
};
